### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by zmaalick** [MetOffice/CATNIP#169]
![image](https://user-images.githubusercontent.com/57943988/100864922-91bcc500-348e-11eb-9cd3-e794b596bad6.png)

**Comment by zmaalick** [comment]
associated branch: hotfix_documentation_i169

**Comment by zmaalick** [comment]
Is this issue has been resolved?

**Comment by balazagi** [comment]
I believe so but it looks like that documentation needs rebuilding on the main branch as the https://metoffice.github.io/CATNIP/#
still has the old content, the latest doc based on the feature branch merged to develop can be seen here:
https://www-nwp/~ssadri/catnip/
